### ISSUE TITLE
Fix Discord ping from Minecraft

### ISSUE THREAD

**Issue by thecatcore** [arthurbambou/Fabric---Discord-Link#101]

**Comment by MightyKnight** [comment]
Not sure what the issue here is. There's barely any description on what is not working.

The closest thing I could gather is ping, but using `@` in Minecraft gives the correct ping on Discord. 
![grafik](https://user-images.githubusercontent.com/38622942/94489499-d5702580-01e4-11eb-9b33-17bc44900cea.png)
So is this about something completely different?

If it's **help wanted** at least some description is essential.

**Comment by thecatcore** [comment]
I wasn’t sure I had fixed it, guess I can close it now.
