### ISSUE TITLE
Channel Description is not always updated

### ISSUE THREAD

**Issue by Azahliil** [arthurbambou/Fabric---Discord-Link#92]
Hey there,
first off, I love this mod! It's amazing what you have done, and that there such a lightweight solution to a discord integration

I just stumbled across one issue, which is that the Channel description for some reason gets stuck to one value.

One server I'm running currently has the channel description 

```
player count : 6/20,
uptime : 0 h 41 min 21 second
```

Even tho the sever has been running for almost 24 hours now, and the number of player fluctuates quite a bit over the day. I think 6 has been the max at one time yet, but I can't really say if that causes the issue.

Currently running FDLInk 0.4.4 on 1.16.1 with fabricApi 0.16 build 384 and lithium 0.5.1

Would be lovely if you could have a look into this :3
Thanks in advance!
~ Aza

**Comment by v-tron** [comment]
This is not a bug but actually discords "fault" since it appears they are rate-limiting how often a bot can change a channel description to twice per 10 minutes (or every 5 minutes):

https://support.discord.com/hc/en-us/community/posts/360067755532-Increase-rate-limit-for-editing-channel-description

Also what I noticed in my testing is that discord seems to queue the API renaming requests. So according to your currently displayed runtime and assuming discord queues all API requests (which looks to be the case from my testing), your server should have been up for about 20.675 hours, which pretty much matches your description. Of course the playercount also shows the number of players who were online at (server start time + uptime). 

Removing this feature is probably a good idea, since it can be implemented via commands like "!status", "!uptime" or "!playercount" and makes the bot compliant with discords rate limits (they can actually API ban you for heavy abuse).

**Comment by Azahliil** [comment]
Oh interesting! 

Thank you so much for that info!

I really like the idea of the commands, but wouldn't it also be possible to just send updated every 10 minutes? I mean it wouldn't be as accurate, but at least a better representation - if you wanna keep that feature in that is.

**Comment by AlexanderRitter02** [comment]
The feature should be kept. Just do it like [DiscordSRV](https://github.com/DiscordSRV/DiscordSRV), I believe they send updates only every X minutes.
